openapi: "3.0.0"
info:
  title: Home Ease API
  description: This is the official documentation for the Home Ease backend
  version: 1.0.0
servers:
  - url: https://home-ease.onrender.com
paths:
  /auth/login:
    $ref: "./resources/auth/login.yaml"
  /auth/register:
    $ref: "./resources/auth/register.yaml"
  /auth/reset-password:
    $ref: "./resources/auth/reset-password/index.yaml"
  /auth/reset-password/{otp}:
    $ref: "./resources/auth/reset-password/otp.yaml"
  /auth/logout:
    $ref: "./resources/auth/logout.yaml"

  /roommates:
    $ref: "./resources/roommate/index.yaml"
  /roommates/{roommateId}:
    $ref: "./resources/roommate/id.yaml"

  /faqs:
    $ref: "./resources/faq/index.yaml"
  /faqs/{faqId}:
    $ref: "./resources/faq/id.yaml"

  /lodges:
    $ref: "./resources/lodge/index.yaml"
  /lodges/{lodgeId}:
    $ref: "./resources/lodge/id.yaml"

  /ecommerce:
    $ref: "./resources/ecommerce/index.yaml"
  /ecommerce/plans:
    $ref: "./resources/ecommerce/plans.yaml"
  /ecommerce/{lodgeId}:
    $ref: "./resources/ecommerce/id.yaml"
  /ecommerce/{lodgeId}/payment-link:
    $ref: "./resources/ecommerce/payment-link.yaml"
components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  tags:
    $ref: "./schemas/tags/_index.yaml"
  securitySchemes:
    $ref: "./schemas/security/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
