name: Publish OpenAPI documentation to GitHub Pages

on:
  push:
    branches: [main, feat/github-workflow]
  workflow_dispatch:
    branches: [main, feat/github-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.26.1

      - name: Build
        run: |
          pnpm build:openapi
          pnpm build:html
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: github-pages
          path: ./_build

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1